# Clippy configuration
# See https://doc.rust-lang.org/clippy/configuration.html

# Configuration options for Clippy lints
# Note: Lint levels (warn/allow/deny) should be configured in Cargo.toml [lints] section
# or using attributes in source code, not in this file.

# Complexity thresholds
type-complexity-threshold = 250
cognitive-complexity-threshold = 30
too-many-arguments-threshold = 7
too-many-lines-threshold = 100

# Size limits
trivial-copy-size-limit = 128
large-error-threshold = 128
pass-by-value-size-limit = 256

# Other configuration
avoid-breaking-exported-api = false
msrv = "1.70"  # Minimum Supported Rust Version
