# Clippy configuration
# See https://doc.rust-lang.org/clippy/configuration.html

# TODO: Review and adjust these lints based on project preferences

# Lint groups to enable
# Note: Some of these might be noisy initially but will improve code quality
warn = [
    "clippy::all",
    "clippy::pedantic",
    "clippy::nursery",
    "clippy::cargo",
]

# Individual lints to allow (disable warnings for these)
allow = [
    # Sometimes we want to use the same name for a field and parameter
    "clippy::similar_names",
    # Module inception is sometimes necessary for clean organization
    "clippy::module_inception",
    # Allow missing errors doc for now (TODO: remove when documentation is complete)
    "clippy::missing_errors_doc",
    # Allow missing panics doc for now (TODO: remove when documentation is complete)
    "clippy::missing_panics_doc",
    # Allow struct excessive bools for now (TODO: review specific cases)
    "clippy::struct_excessive_bools",
    # Allow multiple crate versions during development
    "clippy::multiple_crate_versions",
]

# Individual lints to deny (treat as errors)
deny = [
    # Memory safety and correctness
    "clippy::mem_forget",
    "clippy::indexing_slicing",
    "clippy::unwrap_used",
    "clippy::expect_used",
    
    # Code quality
    "clippy::todo",
    "clippy::unimplemented",
    "clippy::unreachable",
    
    # Performance
    "clippy::clone_on_ref_ptr",
    "clippy::large_stack_arrays",
    "clippy::rc_mutex",
]

# TODO: Configure specific lint limits
# type-complexity-threshold = 250
# trivial-copy-size-limit = 128
# too-many-arguments-threshold = 7
# too-many-lines-threshold = 100
# large-error-threshold = 128
# avoid-breaking-exported-api = false
