name: Release

on:
    release:
        types: [created]

jobs:
    build-windows:
        runs-on: windows-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Deno
          uses: denoland/setup-deno@v1
          with:
            deno-version: v2.x

        - name: Install Deno dependencies
          run: deno install

        - name: Run compile
          run: deno run compile

        - name: Upload compiled files
          uses: actions/upload-artifact@v3
          with:
            name: dist-windows
            path: dist/

    build-linux:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Deno
          uses: denoland/setup-deno@v1
          with:
            deno-version: v2.x

        - name: Install Deno dependencies
          run: deno install

        - name: Run compile
          run: deno run compile

        - name: Upload compiled files
          uses: actions/upload-artifact@v3
          with:
            name: dist-linux
            path: dist/

    build-macos:
        runs-on: macos-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Deno
          uses: denoland/setup-deno@v1
          with:
            deno-version: v2.x

        - name: Install Deno dependencies
          run: deno install

        - name: Run compile
          run: deno run compile

        - name: Upload compiled files
          uses: actions/upload-artifact@v3
          with:
            name: dist-macos
            path: dist/