name: Release

on:
    release:
        types: [created]

jobs:
    build-windows:
        runs-on: windows-latest

        strategy:
            matrix:
                arch: [x64]

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Deno
          uses: denoland/setup-deno@v1
          with:
            deno-version: v2.x

        - name: Install dependencies
          run: deno install
  
        - name: Run package
          run: npm run package-windows-${{ matrix.arch }}

        - name: List release directory for debugging
          run: dir release

        - name: Rename output file
          run: mv release/pacm-${{ matrix.arch }}.exe release/pacm-windows-${{ matrix.arch }}.exe

        - name: Upload compiled files
          uses: actions/upload-artifact@v3
          with:
            name: dist-windows-${{ matrix.arch }}
            path: release/pacm-windows-${{ matrix.arch }}.exe

    build-linux:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                arch: [x64, arm64]

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Deno
          uses: denoland/setup-deno@v1
          with:
            deno-version: v2.x

        - name: Install dependencies
          run: deno install
  
        - name: Run package
          run: npm run package-linux-${{ matrix.arch }}

        - name: List release directory for debugging
          run: ls -la release

        - name: Rename output file
          run: mv release/pacm-${{ matrix.arch }} release/pacm-linux-${{ matrix.arch }}

        - name: Upload compiled files
          uses: actions/upload-artifact@v3
          with:
            name: dist-linux-${{ matrix.arch }}
            path: release/pacm-linux-${{ matrix.arch }}

    build-macos:
        runs-on: macos-latest

        strategy:
            matrix:
                arch: [x64, arm64]

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Deno
          uses: denoland/setup-deno@v1
          with:
            deno-version: v2.x

        - name: Install dependencies
          run: deno install

        - name: Run package
          run: npm run package-macos-${{ matrix.arch }}

        - name: List release directory for debugging
          run: ls -la release

        - name: Rename output file
          run: mv release/pacm-${{ matrix.arch }} release/pacm-macos-${{ matrix.arch }}

        - name: Upload compiled files
          uses: actions/upload-artifact@v3
          with:
            name: dist-macos-${{ matrix.arch }}
            path: release/pacm-macos-${{ matrix.arch }}

    upload-release-assets:
        runs-on: ubuntu-latest
        needs: [build-windows, build-linux, build-macos]
        steps:
        - name: Download Windows artifacts
          uses: actions/download-artifact@v3
          with:
            name: dist-windows-x64
            path: ./dist-windows-x64

        - name: Download Linux artifacts
          uses: actions/download-artifact@v3
          with:
            name: dist-linux-x64
            path: ./dist-linux-x64

        - name: Download Linux artifacts
          uses: actions/download-artifact@v3
          with:
            name: dist-linux-arm64
            path: ./dist-linux-arm64

        - name: Download macOS artifacts
          uses: actions/download-artifact@v3
          with:
            name: dist-macos-x64
            path: ./dist-macos-x64

        - name: Download macOS artifacts
          uses: actions/download-artifact@v3
          with:
            name: dist-macos-arm64
            path: ./dist-macos-arm64

        - name: Verify Windows artifacts
          run: ls -la ./dist-windows-x64

        - name: Verify Linux artifacts
          run: ls -la ./dist-linux-x64 ./dist-linux-arm64

        - name: Verify macOS artifacts
          run: ls -la ./dist-macos-x64 ./dist-macos-arm64

        - name: Upload Windows release assets
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.PAT }}
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ./dist-windows-x64/pacm-windows-x64.exe
            asset_name: pacm-windows-x64.exe
            asset_content_type: application/octet-stream

        - name: Upload Linux release assets
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.PAT }}
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ./dist-linux-x64/pacm-linux-x64
            asset_name: pacm-linux-x64
            asset_content_type: application/octet-stream

        - name: Upload Linux release assets
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.PAT }}
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ./dist-linux-arm64/pacm-linux-arm64
            asset_name: pacm-linux-arm64
            asset_content_type: application/octet-stream

        - name: Upload macOS release assets
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.PAT }}
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ./dist-macos-x64/pacm-macos-x64
            asset_name: pacm-macos-x64
            asset_content_type: application/octet-stream

        - name: Upload macOS release assets
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.PAT }}
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ./dist-macos-arm64/pacm-macos-arm64
            asset_name: pacm-macos-arm64
            asset_content_type: application/octet-stream